apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: s2i-triton
parameters:
  - name: APPLICATION_NAME
    value: s2i-triton
    required: true
  - name: PATCH_PATH
    value: /s2i-triton
    required: true
  - name: DOCKERFILE_PATH
    value: Dockerfile
    required: true
objects:
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  annotations:
    app.openshift.io/vcs-ref: ''
    app.openshift.io/vcs-uri: 'https://github.com/codekow/s2i-patch.git'
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${APPLICATION_NAME}:latest
    runPolicy: SerialLatestOnly
    source:
      contextDir: ${PATCH_PATH}
      git:
        uri: https://github.com/codekow/s2i-patch.git
      type: Git
    strategy:
      dockerStrategy:
        dockerfilePath: ${DOCKERFILE_PATH}
      type: Docker
    triggers:
    - type: ConfigChange
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  annotations:
    app.openshift.io/vcs-ref: ''
    app.openshift.io/vcs-uri: 'https://github.com/codekow/s2i-patch.git'
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    lookupPolicy:
      local: false
    tags:
    - name: latest